//! ShapeNode to TriMesh conversion
//!
//! Converts the CSG tree generated by the evaluator into a triangle mesh.

use ferncad_core::error::{FernError, FernResult};
use ferncad_core::types::ShapeNode;

use crate::bsp;
use crate::mesh::TriMesh;
use crate::primitives;
use crate::transform;

/// Convert a ShapeNode tree to a TriMesh
///
/// # Errors
///
/// Returns an error if child nodes required for CSG operations are missing.
pub fn realize(node: &ShapeNode) -> FernResult<TriMesh> {
    match node {
        // === Primitives ===
        ShapeNode::Box {
            width,
            depth,
            height,
        } => Ok(primitives::generate_box(*width, *depth, *height)),

        ShapeNode::Sphere { radius, segments } => {
            Ok(primitives::generate_sphere(*radius, *segments))
        }

        ShapeNode::Cylinder {
            radius,
            height,
            segments,
        } => Ok(primitives::generate_cylinder(*radius, *height, *segments)),

        ShapeNode::Cone {
            radius_bottom,
            radius_top,
            height,
            segments,
        } => Ok(primitives::generate_cone(
            *radius_bottom,
            *radius_top,
            *height,
            *segments,
        )),

        ShapeNode::Torus {
            radius_major,
            radius_minor,
            segments,
        } => Ok(primitives::generate_torus(
            *radius_major,
            *radius_minor,
            *segments,
        )),

        ShapeNode::Prism {
            sides,
            radius,
            height,
        } => Ok(primitives::generate_prism(*sides, *radius, *height)),

        // === CSG Operations ===
        ShapeNode::Union { children } => {
            if children.is_empty() {
                return Ok(TriMesh::new());
            }
            let mut result = realize(&children[0])?;
            for child in &children[1..] {
                let child_mesh = realize(child)?;
                result = bsp::csg_union(&result, &child_mesh);
            }
            Ok(result)
        }

        ShapeNode::Difference { base, cutters } => {
            let mut result = realize(base)?;
            for cutter in cutters {
                let cutter_mesh = realize(cutter)?;
                result = bsp::csg_difference(&result, &cutter_mesh);
            }
            Ok(result)
        }

        ShapeNode::Intersection { children } => {
            if children.is_empty() {
                return Ok(TriMesh::new());
            }
            let mut result = realize(&children[0])?;
            for child in &children[1..] {
                let child_mesh = realize(child)?;
                result = bsp::csg_intersection(&result, &child_mesh);
            }
            Ok(result)
        }

        // === Transforms ===
        ShapeNode::Translate { shape, offset } => {
            let mut mesh = realize(shape)?;
            transform::translate(&mut mesh, *offset);
            Ok(mesh)
        }

        ShapeNode::Rotate {
            shape,
            axis,
            angle_rad,
        } => {
            let mut mesh = realize(shape)?;
            transform::rotate(&mut mesh, *axis, *angle_rad);
            Ok(mesh)
        }

        ShapeNode::Scale { shape, factors } => {
            let mut mesh = realize(shape)?;
            transform::scale(&mut mesh, *factors);
            Ok(mesh)
        }
    }
}

/// Evaluate source code and convert to a mesh
///
/// Returns the mesh if the last expression evaluates to a Shape.
pub fn eval_and_realize(source: &str) -> FernResult<TriMesh> {
    let mut evaluator = ferncad_core::evaluator::Evaluator::new();
    let result = evaluator.eval_source(source)?;

    match result {
        ferncad_core::types::Value::Shape(node) => realize(&node),
        _ => Err(FernError::CadError {
            message: format!(
                "cannot convert to mesh: the last expression did not return a shape (type: {})",
                result.type_name()
            ),
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    #[test]
    fn test_realize_box() {
        let node = ShapeNode::Box {
            width: 10.0,
            depth: 10.0,
            height: 10.0,
        };
        let mesh = realize(&node).unwrap();
        assert_eq!(mesh.triangle_count(), 12);
        assert_eq!(mesh.vertex_count(), 8);
    }

    #[test]
    fn test_realize_translate() {
        let node = ShapeNode::Translate {
            shape: Arc::new(ShapeNode::Box {
                width: 10.0,
                depth: 10.0,
                height: 10.0,
            }),
            offset: [5.0, 0.0, 0.0],
        };
        let mesh = realize(&node).unwrap();
        let (min, max) = mesh.bounding_box();
        assert!((min[0] - 0.0).abs() < 1e-10);
        assert!((max[0] - 10.0).abs() < 1e-10);
    }

    #[test]
    fn test_realize_union() {
        let node = ShapeNode::Union {
            children: vec![
                Arc::new(ShapeNode::Box {
                    width: 10.0,
                    depth: 10.0,
                    height: 10.0,
                }),
                Arc::new(ShapeNode::Sphere {
                    radius: 5.0,
                    segments: 8,
                }),
            ],
        };
        let mesh = realize(&node).unwrap();
        assert!(mesh.triangle_count() > 0);
    }

    #[test]
    fn test_realize_difference() {
        let node = ShapeNode::Difference {
            base: Arc::new(ShapeNode::Box {
                width: 20.0,
                depth: 20.0,
                height: 20.0,
            }),
            cutters: vec![Arc::new(ShapeNode::Sphere {
                radius: 8.0,
                segments: 8,
            })],
        };
        let mesh = realize(&node).unwrap();
        assert!(mesh.triangle_count() > 0);
    }

    #[test]
    fn test_eval_and_realize() {
        let mesh = eval_and_realize("(box :width 10 :depth 10 :height 10)").unwrap();
        assert_eq!(mesh.triangle_count(), 12);
    }

    #[test]
    fn test_eval_and_realize_with_defpart() {
        let source = r#"
            (defpart my-part
              "テスト"
              :params ((size :: length :default 10.0 :doc "s"))
              :body
              (box :width size :depth size :height size))
            (my-part :size 20.0)
        "#;
        let mesh = eval_and_realize(source).unwrap();
        assert_eq!(mesh.triangle_count(), 12);
        let (_min, max) = mesh.bounding_box();
        assert!((max[0] - 10.0).abs() < 1e-10);
    }
}
